/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Panel;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author z003ywys
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    GridBagLayout layout1 = new GridBagLayout();
    private boolean liga1;
    private boolean liga2;
    private boolean liga3;
    private boolean table;
    private boolean spielplan;
    private boolean clubs;
    public MainView() {
        initComponents();
        liga1 = false;
        liga2 = false;
        liga3 = false;
        table = false;
        spielplan = false;
        clubs = false;
        //GroupLayout layout = new GroupLayout(this.contentView);
        //this.contentView.setLayout(layout);
        //this.contentView.setLayout(layout);
        this.contentView.removeAll();

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        liga1Btn = new javax.swing.JButton();
        liga2Btn = new javax.swing.JButton();
        liga3Btn = new javax.swing.JButton();
        tableBtn = new javax.swing.JButton();
        planBtn = new javax.swing.JButton();
        clubsBtn = new javax.swing.JButton();
        contentView = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        liga1Btn.setBackground(java.awt.Color.lightGray);
        liga1Btn.setLabel("Liga 1");
        liga1Btn.setMaximumSize(new java.awt.Dimension(75, 21));
        liga1Btn.setMinimumSize(new java.awt.Dimension(75, 21));
        liga1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liga1btnClicked(evt);
            }
        });

        liga2Btn.setBackground(java.awt.Color.lightGray);
        liga2Btn.setText("Liga 2");
        liga2Btn.setMaximumSize(new java.awt.Dimension(75, 21));
        liga2Btn.setMinimumSize(new java.awt.Dimension(75, 21));
        liga2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liga2btnClicked(evt);
            }
        });

        liga3Btn.setBackground(java.awt.Color.lightGray);
        liga3Btn.setActionCommand("Liga 3");
        liga3Btn.setLabel("Liga 3");
        liga3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liga3BtnClicked(evt);
            }
        });

        tableBtn.setBackground(java.awt.Color.lightGray);
        tableBtn.setText("Tabelle");
        tableBtn.setMaximumSize(new java.awt.Dimension(75, 21));
        tableBtn.setMinimumSize(new java.awt.Dimension(75, 21));
        tableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableBtnClicked(evt);
            }
        });

        planBtn.setBackground(java.awt.Color.lightGray);
        planBtn.setLabel("Spielplan");
        planBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planBtnClicked(evt);
            }
        });

        clubsBtn.setBackground(java.awt.Color.lightGray);
        clubsBtn.setText("Clubs");
        clubsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubBtnClicked(evt);
            }
        });

        contentView.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setText("Testpanel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        contentView.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(liga1Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addGap(250, 250, 250)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(liga2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(liga3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(planBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clubsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liga1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liga2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liga3Btn))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planBtn)
                    .addComponent(clubsBtn))
                .addGap(26, 26, 26)
                .addComponent(contentView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        liga1Btn.getAccessibleContext().setAccessibleName("liga1btn");
        liga1Btn.getAccessibleContext().setAccessibleDescription("");
        liga2Btn.getAccessibleContext().setAccessibleName("liga2btn");
        liga3Btn.getAccessibleContext().setAccessibleName("liga3btn");
        tableBtn.getAccessibleContext().setAccessibleName("tableBtn");
        planBtn.getAccessibleContext().setAccessibleName("planBtn");
        contentView.getAccessibleContext().setAccessibleName("contentView");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void liga1btnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liga1btnClicked
        // TODO add your handling code here:
        liga1 = true;
        liga1Btn.setBackground(Color.white);
        liga2=false;
        liga2Btn.setBackground(Color.lightGray);
        liga3=false;
        liga3Btn.setBackground(Color.lightGray);
        checkButtons();
    }//GEN-LAST:event_liga1btnClicked

    private void liga2btnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liga2btnClicked
        // TODO add your handling code here:
        liga1 = false;
        liga1Btn.setBackground(Color.lightGray);
        liga2=true;
        liga2Btn.setBackground(Color.white);
        liga3=false;
        liga3Btn.setBackground(Color.lightGray);
        checkButtons();
    }//GEN-LAST:event_liga2btnClicked

    private void planBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planBtnClicked
        // TODO add your handling code here:
        table=false;
        tableBtn.setBackground(Color.lightGray);
        spielplan = true;
        planBtn.setBackground(Color.white);
        clubs = false;
        clubsBtn.setBackground(Color.lightGray);
        checkButtons();
    }//GEN-LAST:event_planBtnClicked

    private void tableBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableBtnClicked
        // TODO add your handling code here:
        table=true;
        tableBtn.setBackground(Color.white);
        spielplan = false;
        planBtn.setBackground(Color.lightGray);
        clubs = false;
        clubsBtn.setBackground(Color.lightGray);
        checkButtons();
    }//GEN-LAST:event_tableBtnClicked

    private void liga3BtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liga3BtnClicked
        // TODO add your handling code here:
        liga1 = false;
        liga1Btn.setBackground(Color.lightGray);
        liga2=false;
        liga2Btn.setBackground(Color.lightGray);
        liga3=true;
        liga3Btn.setBackground(Color.white);
        checkButtons();
    }//GEN-LAST:event_liga3BtnClicked

    private void clubBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubBtnClicked
        // TODO add your handling code here:
        table=false;
        tableBtn.setBackground(Color.lightGray);
        spielplan = false;
        planBtn.setBackground(Color.lightGray);
        clubs = true;
        clubsBtn.setBackground(Color.white);
        checkButtons();
    }//GEN-LAST:event_clubBtnClicked

    /**
     * @param args the command line arguments
     */
    private void checkButtons(){
        //Den View Anpassen über so was wie onproperty changed
        if(liga1 ==true){
            System.out.println("Liga 1 ");
            
            
        }
        if(liga2 == true){
            System.out.println("Liga 2 ");
        }
        if(liga3 == true){
            System.out.println("Liga 3 ");
        }
        if(table == true){
            System.out.println("Table");
            this.contentView.removeAll();
            this.contentView.repaint();
            this.contentView.revalidate();
            //this.contentView.repaint();
            
            this.contentView.add(this.jPanel1);
            this.contentView.repaint();
            this.contentView.revalidate();
            
            
            
            //this.contentView.setVisible(true);
            
        }
        if(spielplan == true){
            System.out.println("Spielplan");
            this.contentView.removeAll();
            this.contentView.repaint();
            this.contentView.revalidate();
        }
        if(clubs == true){
            System.out.println("CLub");
            this.contentView.removeAll();
            this.contentView.repaint();
            this.contentView.revalidate();
        }
        System.out.println("");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainView().setVisible(true);
                
            }
            
        });
       
    }

    public JButton getClubsBtn() {
        return clubsBtn;
    }

    public JButton getLiga1Btn() {
        return liga1Btn;
    }


    public JButton getLiga2Btn() {
        return liga2Btn;
    }

    public JButton getLiga3Btn() {
        return liga3Btn;
    }


    public JButton getPlanBtn() {
        return planBtn;
    }


    public JButton getTableBtn() {
        return tableBtn;
    }
    public void addActionListener (ActionListener listenForButton){
        this.liga1Btn.addActionListener(listenForButton);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clubsBtn;
    private javax.swing.JPanel contentView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton liga1Btn;
    private javax.swing.JButton liga2Btn;
    private javax.swing.JButton liga3Btn;
    private javax.swing.JButton planBtn;
    private javax.swing.JButton tableBtn;
    // End of variables declaration//GEN-END:variables
}
